#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: Release

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      live-run:
        type: boolean
        description: If false (or undefined) the workflow runs in dry-run mode (i.e. with no side-effects)
        required: false
        default: false
      version:
        type: string
        description: Release number. If undefined, the workflow auto-generates a version using git-describe
        required: false
      zenoh-version:
        type: string
        description: Release number of Zenoh. Required in live-run mode and ignored in dry-run mode
        required: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      live-run: ${{ github.event_name == 'schedule' && false || inputs.live-run }}
    steps:
      - run: echo "Setting up inputs..."

  tag:
    needs: setup
    name: Branch, Bump & tag crates
    uses: eclipse-zenoh/ci/.github/workflows/branch-bump-tag-crates.yml@main
    with:
      repo: ${{ github.repository }}
      live-run: ${{ needs.setup.outputs.live-run }}
      version: ${{ inputs.version }}
      bump-deps-pattern: ${{ needs.setup.outputs.live-run && 'zenoh.*' || '^$' }}
      bump-deps-version: ${{ needs.setup.outputs.live-run && inputs.zenoh-version || '' }}
      bump-deps-branch: ${{ needs.setup.outputs.live-run && format('release/{0}', inputs.zenoh-version) || '' }}
    secrets: inherit

  build-debian:
    name: Build Debian packages
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/build-crates-debian.yml@main
    with:
      repo: ${{ github.repository }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
    secrets: inherit

  build-standalone:
    name: Build executables and libraries
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/build-crates-standalone.yml@main
    with:
      repo: ${{ github.repository }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_fs\.(dylib|so)$
        ^zenoh_backend_fs\.dll$
    secrets: inherit

  cargo:
    needs: [setup, tag]
    name: Publish Cargo crates
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-cargo.yml@main
    with:
      repo: ${{ github.repository }}
      live-run: ${{ needs.setup.outputs.live-run }}
      branch: ${{ needs.tag.outputs.branch }}
      # - In dry-run mode, we need to publish eclipse-zenoh/zenoh before this
      #   repository, in which case the version of zenoh dependecies are left as
      #   is and thus point to the main branch of eclipse-zenoh/zenoh.
      # - In live-run mode, we assume that eclipse-zenoh/zenoh is already
      #   published as this workflow can't be responsible for publishing it
      unpublished-deps-patterns: ${{ needs.setup.outputs.live-run && '' || 'zenoh.*' }}
      unpublished-deps-repos: ${{ needs.setup.outputs.live-run && '' || 'eclipse-zenoh/zenoh' }}
    secrets: inherit

  debian:
    name: Publish Debian packages
    needs: [setup, tag, build-debian]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-debian.yml@main
    with:
      no-build: true
      live-run: ${{ needs.setup.outputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
      installation-test: false
    secrets: inherit

  homebrew:
    needs: [setup, tag, build-standalone]
    name: Publish Homebrew formulae
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-homebrew.yml@main
    with:
      no-build: true
      repo: ${{ github.repository }}
      live-run: ${{ needs.setup.outputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_fs\.dylib$
      formulae: |
        zenoh-backend-filesystem
    secrets: inherit

  eclipse:
    name: Publish artifacts to Eclipse downloads
    needs: [setup, tag, build-standalone]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-eclipse.yml@main
    with:
      no-build: true
      live-run: ${{ needs.setup.outputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_fs\.(dylib|so)$
        ^zenoh_backend_fs\.dll$
      name: zenoh-backend-filesystem
    secrets: inherit

  github:
    name: Publish artifacts to GitHub Releases
    needs: [setup, tag, build-standalone]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-github.yml@main
    with:
      no-build: true
      live-run: ${{ needs.setup.outputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_fs\.(dylib|so)$
        ^zenoh_backend_fs\.dll$
    secrets: inherit
